### ISSUE TITLE
Error verifying message: Non-base58 character

### ISSUE THREAD

**Issue by ghost** [blockchainofthings/btc-message-verifier#3]
-

**Comment by claudiosdc** [comment]
This library is NOT expected to work with messages signed with Electrum using segwit addresses. Thus the error that you reported is expected in those cases.

There seems to be a confusion about the usage of this library. It is meant to work for signatures produced ONLY with the bitcoinjs-message library. In particular, whenever a segwit address is used to sign a message, the sigOptions.segwitType property MUST be correctly set (to either 'p2sh(p2wpkh)' or 'p2wpkh'). For more details, please refer to bitcoinjs-message's [Readme file](https://github.com/bitcoinjs/bitcoinjs-message).
